#!/usr/bin/env fish
source (dirname (realpath (status filename)))/helpers.fish

docker build \
  -f "$repo_root/conductor-and-worker/worker/Dockerfile" \
  -t condtest-worker \
  "$repo_root"
  # &

echo -e "Done building worker!\n\n"

docker build \
    -f "$repo_root/conductor-and-worker/conductor/Dockerfile" \
  -t condtest-conductor \
  "$repo_root"

echo -e "Done building conductor!\n\n"
