#!/usr/bin/env fish

# Starts a test Docker worker container with the necessary env vars passed from
# the conductor.

# Testing
set -gx OPENAI_API_KEY (cat ~/downloads/private/openai_api_key.txt)

for required_env_var_name in CONDUCTOR_GRPC_SERVER_ADDR WORKER_ID RUN_DIR
    if not set -q $required_env_var_name
        echo "$required_env_var_name must be set" >&2
        exit 1
    end
end

set worker_image condtest-worker
if set -q WORKER_IMAGE
    set worker_image "$WORKER_IMAGE"
end

set worker_container_name "condtest-worker-$WORKER_ID"

exec docker run \
    --rm \
    --network host \
    --name "$worker_container_name" \
    -e "CONDUCTOR_GRPC_SERVER_ADDR=$CONDUCTOR_GRPC_SERVER_ADDR" \
    -e "WORKER_ID=$WORKER_ID" \
    -e "RUN_DIR=$RUN_DIR" \
    -e "OPENAI_API_KEY=$OPENAI_API_KEY" \
    "$worker_image"
