// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: sharedproto.proto

package sharedproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WorkerEventReceiverService_WorkerStartsHandshake_FullMethodName   = "/sharedproto.WorkerEventReceiverService/WorkerStartsHandshake"
	WorkerEventReceiverService_WorkerStartsShutdown_FullMethodName    = "/sharedproto.WorkerEventReceiverService/WorkerStartsShutdown"
	WorkerEventReceiverService_WorkerRequestsWorkFiles_FullMethodName = "/sharedproto.WorkerEventReceiverService/WorkerRequestsWorkFiles"
	WorkerEventReceiverService_WorkerUploadsFiles_FullMethodName      = "/sharedproto.WorkerEventReceiverService/WorkerUploadsFiles"
	WorkerEventReceiverService_WorkerSendsCodexError_FullMethodName   = "/sharedproto.WorkerEventReceiverService/WorkerSendsCodexError"
)

// WorkerEventReceiverServiceClient is the client API for WorkerEventReceiverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerEventReceiverServiceClient interface {
	WorkerStartsHandshake(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (*HandshakeResponse, error)
	WorkerStartsShutdown(ctx context.Context, in *Shutdown, opts ...grpc.CallOption) (*GeneralResponse, error)
	WorkerRequestsWorkFiles(ctx context.Context, in *FileTransferRequest, opts ...grpc.CallOption) (WorkerEventReceiverService_WorkerRequestsWorkFilesClient, error)
	WorkerUploadsFiles(ctx context.Context, opts ...grpc.CallOption) (WorkerEventReceiverService_WorkerUploadsFilesClient, error)
	WorkerSendsCodexError(ctx context.Context, in *CodexError, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type workerEventReceiverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerEventReceiverServiceClient(cc grpc.ClientConnInterface) WorkerEventReceiverServiceClient {
	return &workerEventReceiverServiceClient{cc}
}

func (c *workerEventReceiverServiceClient) WorkerStartsHandshake(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, WorkerEventReceiverService_WorkerStartsHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerEventReceiverServiceClient) WorkerStartsShutdown(ctx context.Context, in *Shutdown, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, WorkerEventReceiverService_WorkerStartsShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerEventReceiverServiceClient) WorkerRequestsWorkFiles(ctx context.Context, in *FileTransferRequest, opts ...grpc.CallOption) (WorkerEventReceiverService_WorkerRequestsWorkFilesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerEventReceiverService_ServiceDesc.Streams[0], WorkerEventReceiverService_WorkerRequestsWorkFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &workerEventReceiverServiceWorkerRequestsWorkFilesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkerEventReceiverService_WorkerRequestsWorkFilesClient interface {
	Recv() (*FileTransferChunk, error)
	grpc.ClientStream
}

type workerEventReceiverServiceWorkerRequestsWorkFilesClient struct {
	grpc.ClientStream
}

func (x *workerEventReceiverServiceWorkerRequestsWorkFilesClient) Recv() (*FileTransferChunk, error) {
	m := new(FileTransferChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerEventReceiverServiceClient) WorkerUploadsFiles(ctx context.Context, opts ...grpc.CallOption) (WorkerEventReceiverService_WorkerUploadsFilesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerEventReceiverService_ServiceDesc.Streams[1], WorkerEventReceiverService_WorkerUploadsFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &workerEventReceiverServiceWorkerUploadsFilesClient{ClientStream: stream}
	return x, nil
}

type WorkerEventReceiverService_WorkerUploadsFilesClient interface {
	Send(*FileTransferChunk) error
	CloseAndRecv() (*GeneralResponse, error)
	grpc.ClientStream
}

type workerEventReceiverServiceWorkerUploadsFilesClient struct {
	grpc.ClientStream
}

func (x *workerEventReceiverServiceWorkerUploadsFilesClient) Send(m *FileTransferChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerEventReceiverServiceWorkerUploadsFilesClient) CloseAndRecv() (*GeneralResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GeneralResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerEventReceiverServiceClient) WorkerSendsCodexError(ctx context.Context, in *CodexError, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, WorkerEventReceiverService_WorkerSendsCodexError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerEventReceiverServiceServer is the server API for WorkerEventReceiverService service.
// All implementations must embed UnimplementedWorkerEventReceiverServiceServer
// for forward compatibility
type WorkerEventReceiverServiceServer interface {
	WorkerStartsHandshake(context.Context, *Handshake) (*HandshakeResponse, error)
	WorkerStartsShutdown(context.Context, *Shutdown) (*GeneralResponse, error)
	WorkerRequestsWorkFiles(*FileTransferRequest, WorkerEventReceiverService_WorkerRequestsWorkFilesServer) error
	WorkerUploadsFiles(WorkerEventReceiverService_WorkerUploadsFilesServer) error
	WorkerSendsCodexError(context.Context, *CodexError) (*GeneralResponse, error)
	mustEmbedUnimplementedWorkerEventReceiverServiceServer()
}

// UnimplementedWorkerEventReceiverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerEventReceiverServiceServer struct {
}

func (UnimplementedWorkerEventReceiverServiceServer) WorkerStartsHandshake(context.Context, *Handshake) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerStartsHandshake not implemented")
}
func (UnimplementedWorkerEventReceiverServiceServer) WorkerStartsShutdown(context.Context, *Shutdown) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerStartsShutdown not implemented")
}
func (UnimplementedWorkerEventReceiverServiceServer) WorkerRequestsWorkFiles(*FileTransferRequest, WorkerEventReceiverService_WorkerRequestsWorkFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method WorkerRequestsWorkFiles not implemented")
}
func (UnimplementedWorkerEventReceiverServiceServer) WorkerUploadsFiles(WorkerEventReceiverService_WorkerUploadsFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method WorkerUploadsFiles not implemented")
}
func (UnimplementedWorkerEventReceiverServiceServer) WorkerSendsCodexError(context.Context, *CodexError) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerSendsCodexError not implemented")
}
func (UnimplementedWorkerEventReceiverServiceServer) mustEmbedUnimplementedWorkerEventReceiverServiceServer() {
}

// UnsafeWorkerEventReceiverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerEventReceiverServiceServer will
// result in compilation errors.
type UnsafeWorkerEventReceiverServiceServer interface {
	mustEmbedUnimplementedWorkerEventReceiverServiceServer()
}

func RegisterWorkerEventReceiverServiceServer(s grpc.ServiceRegistrar, srv WorkerEventReceiverServiceServer) {
	s.RegisterService(&WorkerEventReceiverService_ServiceDesc, srv)
}

func _WorkerEventReceiverService_WorkerStartsHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handshake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerEventReceiverServiceServer).WorkerStartsHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerEventReceiverService_WorkerStartsHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerEventReceiverServiceServer).WorkerStartsHandshake(ctx, req.(*Handshake))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerEventReceiverService_WorkerStartsShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Shutdown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerEventReceiverServiceServer).WorkerStartsShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerEventReceiverService_WorkerStartsShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerEventReceiverServiceServer).WorkerStartsShutdown(ctx, req.(*Shutdown))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerEventReceiverService_WorkerRequestsWorkFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileTransferRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerEventReceiverServiceServer).WorkerRequestsWorkFiles(m, &workerEventReceiverServiceWorkerRequestsWorkFilesServer{ServerStream: stream})
}

type WorkerEventReceiverService_WorkerRequestsWorkFilesServer interface {
	Send(*FileTransferChunk) error
	grpc.ServerStream
}

type workerEventReceiverServiceWorkerRequestsWorkFilesServer struct {
	grpc.ServerStream
}

func (x *workerEventReceiverServiceWorkerRequestsWorkFilesServer) Send(m *FileTransferChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkerEventReceiverService_WorkerUploadsFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerEventReceiverServiceServer).WorkerUploadsFiles(&workerEventReceiverServiceWorkerUploadsFilesServer{ServerStream: stream})
}

type WorkerEventReceiverService_WorkerUploadsFilesServer interface {
	SendAndClose(*GeneralResponse) error
	Recv() (*FileTransferChunk, error)
	grpc.ServerStream
}

type workerEventReceiverServiceWorkerUploadsFilesServer struct {
	grpc.ServerStream
}

func (x *workerEventReceiverServiceWorkerUploadsFilesServer) SendAndClose(m *GeneralResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerEventReceiverServiceWorkerUploadsFilesServer) Recv() (*FileTransferChunk, error) {
	m := new(FileTransferChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WorkerEventReceiverService_WorkerSendsCodexError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodexError)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerEventReceiverServiceServer).WorkerSendsCodexError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerEventReceiverService_WorkerSendsCodexError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerEventReceiverServiceServer).WorkerSendsCodexError(ctx, req.(*CodexError))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerEventReceiverService_ServiceDesc is the grpc.ServiceDesc for WorkerEventReceiverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerEventReceiverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sharedproto.WorkerEventReceiverService",
	HandlerType: (*WorkerEventReceiverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkerStartsHandshake",
			Handler:    _WorkerEventReceiverService_WorkerStartsHandshake_Handler,
		},
		{
			MethodName: "WorkerStartsShutdown",
			Handler:    _WorkerEventReceiverService_WorkerStartsShutdown_Handler,
		},
		{
			MethodName: "WorkerSendsCodexError",
			Handler:    _WorkerEventReceiverService_WorkerSendsCodexError_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkerRequestsWorkFiles",
			Handler:       _WorkerEventReceiverService_WorkerRequestsWorkFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WorkerUploadsFiles",
			Handler:       _WorkerEventReceiverService_WorkerUploadsFiles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sharedproto.proto",
}
