// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type SqsAlarmMessage struct {
	ID                                 int64  `json:"id"`
	ReceivedAt                         string `json:"received_at"`
	RawMessageBody                     string `json:"raw_message_body"`
	AwsAccountNumber                   string `json:"aws_account_number"`
	ReturnedSpawnDecisionForChainedSet int64  `json:"returned_spawn_decision_for_chained_set"`
	IsChained                          int64  `json:"is_chained"`
}

type SqsTicketMessage struct {
	ID                             int64  `json:"id"`
	ReceivedAt                     string `json:"received_at"`
	RawMessageBody                 string `json:"raw_message_body"`
	AwsAccountNumber               string `json:"aws_account_number"`
	ReturnedSpawnDecisionForTicket int64  `json:"returned_spawn_decision_for_ticket"`
}
