// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sqs_alarm_mesages_queries.sql

package sqlcgen

import (
	"context"
)

const insertSQSAlarmMessage = `-- name: InsertSQSAlarmMessage :one
INSERT INTO sqs_alarm_messages (
    raw_message_body,
    aws_account_number
) VALUES (
    ?, ?
)
RETURNING id,
          received_at,
          raw_message_body,
          aws_account_number,
          returned_spawn_decision_for_chained_set,
          is_chained
`

type InsertSQSAlarmMessageParams struct {
	RawMessageBody   string `json:"raw_message_body"`
	AwsAccountNumber string `json:"aws_account_number"`
}

func (q *Queries) InsertSQSAlarmMessage(ctx context.Context, arg InsertSQSAlarmMessageParams) (SqsAlarmMessage, error) {
	row := q.db.QueryRowContext(ctx, insertSQSAlarmMessage, arg.RawMessageBody, arg.AwsAccountNumber)
	var i SqsAlarmMessage
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.RawMessageBody,
		&i.AwsAccountNumber,
		&i.ReturnedSpawnDecisionForChainedSet,
		&i.IsChained,
	)
	return i, err
}

const insertSQSAlarmMessageAt = `-- name: InsertSQSAlarmMessageAt :one
INSERT INTO sqs_alarm_messages (
    received_at,
    raw_message_body,
    aws_account_number
) VALUES (
    ?, ?, ?
)
RETURNING id,
          received_at,
          raw_message_body,
          aws_account_number,
          returned_spawn_decision_for_chained_set,
          is_chained
`

type InsertSQSAlarmMessageAtParams struct {
	ReceivedAt       string `json:"received_at"`
	RawMessageBody   string `json:"raw_message_body"`
	AwsAccountNumber string `json:"aws_account_number"`
}

func (q *Queries) InsertSQSAlarmMessageAt(ctx context.Context, arg InsertSQSAlarmMessageAtParams) (SqsAlarmMessage, error) {
	row := q.db.QueryRowContext(ctx, insertSQSAlarmMessageAt, arg.ReceivedAt, arg.RawMessageBody, arg.AwsAccountNumber)
	var i SqsAlarmMessage
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.RawMessageBody,
		&i.AwsAccountNumber,
		&i.ReturnedSpawnDecisionForChainedSet,
		&i.IsChained,
	)
	return i, err
}

const insertSQSTicketMessage = `-- name: InsertSQSTicketMessage :one
INSERT INTO sqs_ticket_messages (
    raw_message_body,
    aws_account_number
) VALUES (
    ?, ?
)
RETURNING id,
          received_at,
          raw_message_body,
          aws_account_number,
          returned_spawn_decision_for_ticket
`

type InsertSQSTicketMessageParams struct {
	RawMessageBody   string `json:"raw_message_body"`
	AwsAccountNumber string `json:"aws_account_number"`
}

func (q *Queries) InsertSQSTicketMessage(ctx context.Context, arg InsertSQSTicketMessageParams) (SqsTicketMessage, error) {
	row := q.db.QueryRowContext(ctx, insertSQSTicketMessage, arg.RawMessageBody, arg.AwsAccountNumber)
	var i SqsTicketMessage
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.RawMessageBody,
		&i.AwsAccountNumber,
		&i.ReturnedSpawnDecisionForTicket,
	)
	return i, err
}

const listSQSAlarmMessages = `-- name: ListSQSAlarmMessages :many
SELECT id,
       received_at,
       raw_message_body,
       aws_account_number,
       returned_spawn_decision_for_chained_set,
       is_chained
FROM sqs_alarm_messages
ORDER BY aws_account_number ASC, received_at ASC, id ASC
`

func (q *Queries) ListSQSAlarmMessages(ctx context.Context) ([]SqsAlarmMessage, error) {
	rows, err := q.db.QueryContext(ctx, listSQSAlarmMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SqsAlarmMessage
	for rows.Next() {
		var i SqsAlarmMessage
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.RawMessageBody,
			&i.AwsAccountNumber,
			&i.ReturnedSpawnDecisionForChainedSet,
			&i.IsChained,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSQSTicketMessagesNeedingDecision = `-- name: ListSQSTicketMessagesNeedingDecision :many
SELECT id,
       received_at,
       raw_message_body,
       aws_account_number,
       returned_spawn_decision_for_ticket
FROM sqs_ticket_messages
WHERE returned_spawn_decision_for_ticket = 0
ORDER BY received_at ASC, id ASC
`

func (q *Queries) ListSQSTicketMessagesNeedingDecision(ctx context.Context) ([]SqsTicketMessage, error) {
	rows, err := q.db.QueryContext(ctx, listSQSTicketMessagesNeedingDecision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SqsTicketMessage
	for rows.Next() {
		var i SqsTicketMessage
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.RawMessageBody,
			&i.AwsAccountNumber,
			&i.ReturnedSpawnDecisionForTicket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSQSAlarmMessageChained = `-- name: MarkSQSAlarmMessageChained :execrows
UPDATE sqs_alarm_messages
SET is_chained = 1
WHERE id = ?
`

func (q *Queries) MarkSQSAlarmMessageChained(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSQSAlarmMessageChained, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSQSAlarmMessageSpawnDecision = `-- name: SetSQSAlarmMessageSpawnDecision :execrows
UPDATE sqs_alarm_messages
SET returned_spawn_decision_for_chained_set = ?
WHERE id = ?
`

type SetSQSAlarmMessageSpawnDecisionParams struct {
	ReturnedSpawnDecisionForChainedSet int64 `json:"returned_spawn_decision_for_chained_set"`
	ID                                 int64 `json:"id"`
}

func (q *Queries) SetSQSAlarmMessageSpawnDecision(ctx context.Context, arg SetSQSAlarmMessageSpawnDecisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSQSAlarmMessageSpawnDecision, arg.ReturnedSpawnDecisionForChainedSet, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSQSTicketMessageSpawnDecision = `-- name: SetSQSTicketMessageSpawnDecision :execrows
UPDATE sqs_ticket_messages
SET returned_spawn_decision_for_ticket = ?
WHERE id = ?
`

type SetSQSTicketMessageSpawnDecisionParams struct {
	ReturnedSpawnDecisionForTicket int64 `json:"returned_spawn_decision_for_ticket"`
	ID                             int64 `json:"id"`
}

func (q *Queries) SetSQSTicketMessageSpawnDecision(ctx context.Context, arg SetSQSTicketMessageSpawnDecisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSQSTicketMessageSpawnDecision, arg.ReturnedSpawnDecisionForTicket, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
