#!/usr/bin/env fish
source (dirname (realpath (status filename)))/helpers.fish
cdgit
fd '\.go$' . --exclude proto --exclude sqlc-generated -x gofumpt -l || exit 1
fd '\.go$' . --exclude proto --exclude sqlc-generated -x gofumpt -w
