#!/usr/bin/env fish

set queue_url (set -q FAUX_SQS_QUEUE_URL; and echo $FAUX_SQS_QUEUE_URL; or echo "https://sqs.us-west-2.amazonaws.com/204772699175/agent-operation-events")
set region (set -q FAUX_AWS_REGION; and echo $FAUX_AWS_REGION; or echo "us-west-2")
set account_id (set -q FAUX_ACCOUNT_ID; and echo $FAUX_ACCOUNT_ID; or echo "204772699175")
set alarm_name (set -q FAUX_ALARM_NAME; and echo $FAUX_ALARM_NAME; or echo "debian-cpu-spin-high-cpu")
set instance_id (set -q FAUX_INSTANCE_ID; and echo $FAUX_INSTANCE_ID; or echo "i-03f8306225046aca5")
set event_id (set -q FAUX_EVENT_ID; and echo $FAUX_EVENT_ID; or python3 -c 'import uuid; print(uuid.uuid4())')
set event_time (set -q FAUX_EVENT_TIME; and echo $FAUX_EVENT_TIME; or date -u +"%Y-%m-%dT%H:%M:%SZ")
set reason (set -q FAUX_REASON; and echo $FAUX_REASON; or echo "Faux test alert: generated by scripts/push-faux-sqs-alert.fish")
set state_value (set -q FAUX_STATE_VALUE; and echo $FAUX_STATE_VALUE; or echo "ALARM")
set previous_state_value (set -q FAUX_PREVIOUS_STATE_VALUE; and echo $FAUX_PREVIOUS_STATE_VALUE; or echo "OK")
set previous_reason (set -q FAUX_PREVIOUS_REASON; and echo $FAUX_PREVIOUS_REASON; or echo "Faux previous state.")
set query_date (set -q FAUX_QUERY_DATE; and echo $FAUX_QUERY_DATE; or echo $event_time)
set start_date (set -q FAUX_START_DATE; and echo $FAUX_START_DATE; or echo $event_time)
set state_timestamp (set -q FAUX_STATE_TIMESTAMP; and echo $FAUX_STATE_TIMESTAMP; or echo $event_time)
set previous_query_date (set -q FAUX_PREVIOUS_QUERY_DATE; and echo $FAUX_PREVIOUS_QUERY_DATE; or echo $event_time)
set previous_state_timestamp (set -q FAUX_PREVIOUS_STATE_TIMESTAMP; and echo $FAUX_PREVIOUS_STATE_TIMESTAMP; or echo $event_time)
set datapoint (set -q FAUX_DATAPOINT; and echo $FAUX_DATAPOINT; or echo "99.83")
set previous_datapoint (set -q FAUX_PREVIOUS_DATAPOINT; and echo $FAUX_PREVIOUS_DATAPOINT; or echo "10.1")
set threshold (set -q FAUX_THRESHOLD; and echo $FAUX_THRESHOLD; or echo "20.0")
set period (set -q FAUX_PERIOD; and echo $FAUX_PERIOD; or echo "20")
set metric_id (set -q FAUX_METRIC_ID; and echo $FAUX_METRIC_ID; or echo "faux-cpu-metric")
set description (set -q FAUX_DESCRIPTION; and echo $FAUX_DESCRIPTION; or echo "Faux high CPU alert for local agent-operation testing")

set message_body (env \
    EVENT_ID="$event_id" \
    EVENT_TIME="$event_time" \
    AWS_REGION="$region" \
    ACCOUNT_ID="$account_id" \
    ALARM_NAME="$alarm_name" \
    INSTANCE_ID="$instance_id" \
    REASON="$reason" \
    STATE_VALUE="$state_value" \
    PREVIOUS_STATE_VALUE="$previous_state_value" \
    PREVIOUS_REASON="$previous_reason" \
    QUERY_DATE="$query_date" \
    START_DATE="$start_date" \
    STATE_TIMESTAMP="$state_timestamp" \
    PREVIOUS_QUERY_DATE="$previous_query_date" \
    PREVIOUS_STATE_TIMESTAMP="$previous_state_timestamp" \
    DATAPOINT="$datapoint" \
    PREVIOUS_DATAPOINT="$previous_datapoint" \
    THRESHOLD="$threshold" \
    PERIOD="$period" \
    METRIC_ID="$metric_id" \
    DESCRIPTION="$description" \
    python3 -c '
import json
import os

datapoint = float(os.environ["DATAPOINT"])
previous_datapoint = os.environ["PREVIOUS_DATAPOINT"]
threshold = float(os.environ["THRESHOLD"])
period = int(os.environ["PERIOD"])

previous_recent_datapoints = []
if previous_datapoint:
    previous_recent_datapoints = [float(previous_datapoint)]

alarm_arn = "arn:aws:cloudwatch:{}:{}:alarm:{}".format(
    os.environ["AWS_REGION"],
    os.environ["ACCOUNT_ID"],
    os.environ["ALARM_NAME"],
)

event = {
    "version": "0",
    "id": os.environ["EVENT_ID"],
    "detail-type": "CloudWatch Alarm State Change",
    "source": "aws.cloudwatch",
    "account": os.environ["ACCOUNT_ID"],
    "time": os.environ["EVENT_TIME"],
    "region": os.environ["AWS_REGION"],
    "resources": [
        alarm_arn
    ],
    "detail": {
        "alarmName": os.environ["ALARM_NAME"],
        "state": {
            "value": os.environ["STATE_VALUE"],
            "reason": os.environ["REASON"],
            "reasonData": json.dumps({
                "version": "1.0",
                "queryDate": os.environ["QUERY_DATE"],
                "startDate": os.environ["START_DATE"],
                "statistic": "Average",
                "period": period,
                "recentDatapoints": [datapoint],
                "threshold": threshold,
                "evaluatedDatapoints": [
                    {
                        "timestamp": os.environ["START_DATE"],
                        "sampleCount": 1.0,
                        "value": datapoint,
                    }
                ],
            }),
            "timestamp": os.environ["STATE_TIMESTAMP"],
        },
        "previousState": {
            "value": os.environ["PREVIOUS_STATE_VALUE"],
            "reason": os.environ["PREVIOUS_REASON"],
            "reasonData": json.dumps({
                "version": "1.0",
                "queryDate": os.environ["PREVIOUS_QUERY_DATE"],
                "statistic": "Average",
                "period": period,
                "recentDatapoints": previous_recent_datapoints,
                "threshold": threshold,
                "evaluatedDatapoints": [
                    {
                        "timestamp": os.environ["PREVIOUS_STATE_TIMESTAMP"],
                    }
                ],
            }),
            "timestamp": os.environ["PREVIOUS_STATE_TIMESTAMP"],
        },
        "configuration": {
            "metrics": [
                {
                    "id": os.environ["METRIC_ID"],
                    "metricStat": {
                        "metric": {
                            "namespace": "AWS/EC2",
                            "name": "CPUUtilization",
                            "dimensions": {
                                "InstanceId": os.environ["INSTANCE_ID"],
                            },
                        },
                        "period": period,
                        "stat": "Average",
                    },
                    "returnData": True,
                }
            ],
            "description": os.environ["DESCRIPTION"],
        },
    },
}

print(json.dumps(event, separators=(",", ":")))
')

if test $status -ne 0
    echo "failed to build faux sqs message body" >&2
    exit 1
end

if test -z "$message_body"
    echo "failed to build faux sqs message body: empty message body" >&2
    exit 1
end

aws sqs send-message \
    --queue-url "$queue_url" \
    --region "$region" \
    --message-body "$message_body" >/dev/null

echo "sent faux sqs alert event_id=$event_id"
