// Code generated by "stringer -type=workerEvent -linecomment serverside-worker.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WorkerEventSpawnStarted-0]
	_ = x[WorkerEventHandshakeSucceeded-1]
	_ = x[WorkerEventHandshakeFailed-2]
	_ = x[WorkerEventGotFilesSucceeded-3]
	_ = x[WorkerEventGotFilesFailed-4]
	_ = x[WorkerEventUploadedFilesSucceeded-5]
	_ = x[WorkerEventStartsTest-6]
	_ = x[WorkerEventCodexError-7]
	_ = x[WorkerEventSafelyEnded-8]
	_ = x[WorkerEventBadlyEnded-9]
}

const _workerEvent_name = "worker_spawn_startedworker_handshake_succeededworker_handshake_failedworker_got_files_succeededworker_got_files_failedworker_uploaded_files_succeededworker_starts_testworker_codex_errorworker_safely_endedworker_badly_ended"

var _workerEvent_index = [...]uint8{0, 20, 46, 69, 95, 118, 149, 167, 185, 204, 222}

func (i workerEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_workerEvent_index)-1 {
		return "workerEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _workerEvent_name[_workerEvent_index[idx]:_workerEvent_index[idx+1]]
}
